### ISSUE TITLE
implement promise tab skeleton

### ISSUE THREAD

**Issue by coitloz88** [coitloz88/alcohol-free#19]
이슈를 안 만들어뒀네요...😅

약속 탭 UI 픽스된 것 위주로 만들고 있습니다!

![promise tab](https://user-images.githubusercontent.com/88723775/225031886-5fa19651-13f6-49f4-a0a2-0f2eab0a438e.png)

**Comment by coitloz88** [comment]
중간에 있는 card?들부터 만들고 있습니다. 이런 너낌
![card view](https://user-images.githubusercontent.com/88723775/225255449-e69b8564-4f07-4e31-a3dd-5b8a7cdf8d59.png)

세부적인 pixel단위의 디자인은 차차 반영하겠습니다...🥲

**Comment by coitloz88** [comment]
https://velog.io/@tygerhwang/Flutter-Tab-View-%EB%A7%8C%EB%93%A4%EA%B8%B01-Tabbar

**Comment by coitloz88** [comment]
진행 상황

![image](https://user-images.githubusercontent.com/88723775/226684152-f2b5aaa0-43fc-4c84-af5f-872788cd8c6b.png)

**Comment by coitloz88** [comment]
#TODO

`나의 약속` 탭에서,

- [ ] sort 기능 활성화: 시작한 날짜 기준?
- [ ] 스트링 정리
- [ ] 혼자하는 약속과 여럿이서 하는 약속 구분
- [ ] 관련해서, 함께 하는지 아닌지에 따라 hand icon 숨기는 것 구현
- [ ] 관련해서, 함께하는 명수만큼 프로필 노출 및 3인 이상일때 생략 표현

**Comment by coitloz88** [comment]
`sizer`로 화면 크기 기반 계산 가능
